In [1]:
# Load data for weather

import numpy as np
import pandas as pd

df_wthr = pd.read_csv(r'C:/Users/caral/OneDrive - KTH/SUPD/Year 2/AI in Transportation/matdata_Stockholm_2016-01-01_2026-01-01_timmedel.csv', sep=';', encoding='latin-1')

df_wthr.drop(['Tidpunkt', 'DATE (raw)', 'time (raw1)'], axis=1, inplace=True)

df_wthr.rename(columns={"time (raw 2)": "time", "Byvind (m/s)": "wind_peak", "Solinstrålning (W/m²)": "solar_rad", "Nederbörd (mm)": "rain", "Rel. fuktighet (%)": "hum", 
                        "Temperatur (°C)": "temp", "Lufttryck (hPa)": "air_pre", "Vindhastighet (m/s)": "wind_spe", "Vindriktning (°)": "wind_dir"}, inplace=True, errors="raise")

df_wthr['date_time'] = np.where(df_wthr['time']//3600 < 10, 
                                       df_wthr['date'].astype(str) + '_0' + (df_wthr['time']//3600).astype(str), 
                                       df_wthr['date'].astype(str) + '_' + (df_wthr['time']//3600).astype(str))

df_wthr.head(10)

,date,time,wind_peak,solar_rad,rain,hum,temp,air_pre,wind_spe,wind_dir,...,wind_dir-1,wind_peak-2,solar_rad-2,rain-2,hum-2,temp-2,air_pre-2,wind_spe-2,wind_dir-2,date_time
0,20240101,0,8.5,0.0,0.0,71.1,-2.1,1010.5,4.2,80.5,...,80.5,8.5,0.0,0.0,71.1,-2.1,1010.5,4.2,80.5,20240101_00
1,20240101,3600,8.5,0.0,0.0,72.0,-2.2,1010.0,4.2,83.7,...,80.5,8.5,0.0,0.0,71.1,-2.1,1010.5,4.2,80.5,20240101_01
2,20240101,7200,8.1,0.0,0.0,72.3,-2.2,1010.0,4.3,85.0,...,83.7,8.5,0.0,0.0,71.1,-2.1,1010.5,4.2,80.5,20240101_02
3,20240101,10800,10.1,0.0,0.0,70.5,-1.9,1010.0,5.4,98.9,...,85.0,8.5,0.0,0.0,72.0,-2.2,1010.0,4.2,83.7,20240101_03
4,20240101,14400,8.3,0.0,0.0,70.3,-1.7,1010.0,4.6,99.4,...,98.9,8.1,0.0,0.0,72.3,-2.2,1010.0,4.3,85.0,20240101_04
5,20240101,18000,10.0,0.0,0.0,72.9,-1.6,1009.0,6.2,106.9,...,99.4,10.1,0.0,0.0,70.5,-1.9,1010.0,5.4,98.9,20240101_05
6,20240101,21600,9.0,0.0,0.0,75.1,-2.0,1009.5,4.4,111.9,...,106.9,8.3,0.0,0.0,70.3,-1.7,1010.0,4.6,99.4,20240101_06
7,20240101,25200,7.9,0.0,0.0,73.4,-2.0,1009.2,4.1,94.5,...,111.9,10.0,0.0,0.0,72.9,-1.6,1009.0,6.2,106.9,20240101_07
8,20240101,28800,9.6,0.0,0.0,75.2,-1.8,1010.0,4.5,104.3,...,94.5,9.0,0.0,0.0,75.1,-2.0,1009.5,4.4,111.9,20240101_08
9,20240101,32400,8.8,0.3,0.0,79.9,-1.8,1010.0,4.1,100.9,...,104.3,7.9,0.0,0.0,73.4,-2.0,1009.2,4.1,94.5,20240101_09

In [2]:
# Load data for coordinates

import pandas as pd

df_allstop = pd.read_csv(r'C:/Users/caral/OneDrive - KTH/SUPD/Year 2/AI in Transportation/stops_coord.csv', sep=',')

df_allstop.rename(columns={"stop_id": "observed_StopAreaID"}, inplace=True, errors="raise")
df_allstop.drop(['stop_name', 'stop_lat', 'stop_lon', 'location_t', 'parent_sta', 'platform_c'], axis=1, inplace=True)

df_allstop.head(10)

   observed_StopAreaID             x             y
0     9021001000101000  190165.49645  6.574786e+06
1     9021001000102000  191696.35433  6.574110e+06
2     9021001000103000  192276.89356  6.566156e+06
3     9021001000104000  193030.55915  6.566956e+06
4     9021001000105000  193294.11216  6.565674e+06
5     9021001000106000  192277.40069  6.564900e+06
6     9021001000107000  191127.58728  6.564238e+06
7     9021001000108000  190407.22661  6.563777e+06
8     9021001000109000  190042.67580  6.563461e+06
9     9021001000110000  190057.42071  6.562988e+06

In [146]:
# Load data for delays and bus origin

import pandas as pd

df_bus = pd.read_csv(r'C:/Users/caral/OneDrive - KTH/SUPD/Year 2/AI in Transportation/gtfs_rt_202406.csv', sep=';', encoding='latin-1')

df_bus.info()

C:\Users\caral\AppData\Local\Temp\ipykernel_39412\1945775193.py:5: DtypeWarning: Columns (0: LineNumber, 1: route_id) have mixed types. Specify dtype option on import or set low_memory=False.
  df_bus = pd.read_csv(r'C:/Users/caral/OneDrive - KTH/SUPD/Year 2/AI in Transportation/gtfs_rt_202406.csv', sep=';', encoding='latin-1')

<class 'pandas.DataFrame'>
RangeIndex: 16997406 entries, 0 to 16997405
Data columns (total 28 columns):
 #   Column                                             Dtype
---  ------                                             -----
 0   date                                               int64
 1   LineNumber                                         object
 2   LineID                                             int64
 3   route_id                                           object
 4   TransportMode                                      str
 5   direction_id                                       int64
 6   trip_id                                            int64
 7   VehicleID                                          float64
 8   shape_id                                           int64
 9   planned_departure_sfm                              int64
 10  planned_departure_tripupdates_sfm                  float64
 11  stop_sequence                                      int64
 12  dist_traveled                                      float64
 13  previous_stop_id                                   int64
 14  previous_StopAreaID                                int64
 15  observed_stop_id                                   int64
 16  observed_StopAreaID                                int64
 17  scheduled_arrival_time_sfm                         int64
 18  observed_arrival_time_sfm                          float64
 19  observed_arrival_delay                             float64
 20  observed_arrival_uncertainty                       float64
 21  scheduled_departure_time_sfm                       int64
 22  observed_departure_time_sfm                        float64
 23  observed_departure_delay                           float64
 24  observed_departure_uncertainty                     float64
 25  tripupdates_and_gtfs_not_merged_within_service_id  str
 26  tripupdates_not_merged_with_stoptimes_or_trip      str
 27  stop_headsign                                      str
dtypes: float64(9), int64(13), object(2), str(4)
memory usage: 3.5+ GB

In [147]:
# Geting initial delay

df_bus['ini_delay'] = (
    df_bus['observed_arrival_delay']
    .where(df_bus['stop_sequence'].eq(1))
    .ffill())

In [148]:
# Extracting information of routes

df_routes = df_bus[df_bus['stop_sequence']==1]
df_routes['LineID_direction'] = df_routes['LineID'].astype(str) + '_' + df_routes['direction_id'].astype(str)
df_routes = df_routes.drop_duplicates(subset=['LineID_direction'], keep='first')

In [149]:
# Filtering to stops in area and bus

model_stops = (9021001000308000,9021001000315000,9021001001011000,9021001001511000,9021001001521000,9021001002511000,9021001002521000,9021001002531000,
               9021001005131000,9021001007631000,9021001008016000,9021001010130000,9021001010132000,9021001010133000,9021001010136000,9021001010137000,
               9021001010144000,9021001010152000,9021001010248000,9021001010250000,9021001010251000,9021001010252000,9021001010253000,9021001010254000,
               9021001010255000,9021001010256000,9021001010258000,9021001010261000,9021001010263000,9021001010393000,9021001010395000,9021001010397000,
               9021001010401000,9021001010406000,9021001010410000,9021001010415000,9021001010491000,9021001010494000,9021001010527000,9021001010573000,
               9021001010591000,9021001010592000,9021001010593000,9021001010629000,9021001010647000,9021001010649000,9021001010651000,9021001010653000,
               9021001010655000,9021001010657000,9021001010658000,9021001010659000,9021001010661000,9021001010668000,9021001010701000,9021001010703000,
               9021001010705000,9021001010707000,9021001010763000,9021001010765000,9021001010768000,9021001010771000,9021001010777000,9021001010813000,
               9021001010814000,9021001010817000,9021001010821000,9021001010824000,9021001010877000,9021001010878000,9021001010881000,9021001010882000,
               9021001010953000,9021001010955000,9021001010956000,9021001010957000,9021001010960000,9021001010961000,9021001010963000,9021001010965000,
               9021001010967000,9021001010971000,9021001010976000,9021001010979000,9021001010984000,9021001011002000,9021001040088000,9021001044000000,
               9021001044200000,9021001070692000,9022001000308000,9022001000315000,9022001001011000,9022001001011000,9022001001011000,9022001001011000,
               9022001001511000,9022001001511000,9022001001521000,9022001001521000,9022001002511000,9022001002511000,9022001002521000,9022001002521000,
               9022001002531000,9022001002531000,9022001005131000,9022001005131000,9022001005131000,9022001005131000,9022001007631000,9022001008016000,
               9022001010130000,9022001010130000,9022001010130000,9022001010130000,9022001010132000,9022001010132000,9022001010133000,9022001010133000,
               9022001010136000,9022001010136000,9022001010137000,9022001010137000,9022001010144000,9022001010144000,9022001010152000,9022001010152000,
               9022001010248000,9022001010248000,9022001010248000,9022001010248000,9022001010250000,9022001010250000,9022001010251000,9022001010251000,
               9022001010252000,9022001010252000,9022001010253000,9022001010253000,9022001010254000,9022001010254000,9022001010254000,9022001010255000,
               9022001010255000,9022001010255000,9022001010256000,9022001010256000,9022001010258000,9022001010258000,9022001010261000,9022001010261000,
               9022001010261000,9022001010261000,9022001010261000,9022001010261000,9022001010261000,9022001010261000,9022001010263000,9022001010263000,
               9022001010393000,9022001010393000,9022001010395000,9022001010395000,9022001010397000,9022001010397000,9022001010397000,9022001010397000,
               9022001010401000,9022001010401000,9022001010406000,9022001010406000,9022001010406000,9022001010410000,9022001010415000,9022001010415000,
               9022001010415000,9022001010491000,9022001010491000,9022001010494000,9022001010494000,9022001010527000,9022001010527000,9022001010573000,
               9022001010573000,9022001010591000,9022001010591000,9022001010591000,9022001010591000,9022001010591000,9022001010592000,9022001010593000,
               9022001010629000,9022001010629000,9022001010647000,9022001010647000,9022001010649000,9022001010649000,9022001010649000,9022001010649000,
               9022001010649000,9022001010649000,9022001010649000,9022001010651000,9022001010651000,9022001010653000,9022001010653000,9022001010655000,
               9022001010655000,9022001010655000,9022001010657000,9022001010658000,9022001010658000,9022001010659000,9022001010659000,9022001010661000,
               9022001010661000,9022001010668000,9022001010668000,9022001010701000,9022001010701000,9022001010703000,9022001010703000,9022001010705000,
               9022001010705000,9022001010707000,9022001010707000,9022001010763000,9022001010763000,9022001010765000,9022001010765000,9022001010768000,
               9022001010768000,9022001010771000,9022001010771000,9022001010777000,9022001010777000,9022001010813000,9022001010813000,9022001010813000,
               9022001010813000,9022001010814000,9022001010814000,9022001010817000,9022001010817000,9022001010821000,9022001010821000,9022001010821000,
               9022001010824000,9022001010877000,9022001010877000,9022001010878000,9022001010878000,9022001010881000,9022001010881000,9022001010881000,
               9022001010882000,9022001010882000,9022001010953000,9022001010953000,9022001010955000,9022001010955000,9022001010956000,9022001010956000,
               9022001010957000,9022001010960000,9022001010961000,9022001010961000,9022001010963000,9022001010963000,9022001010965000,9022001010965000,
               9022001010967000,9022001010967000,9022001010971000,9022001010976000,9022001010976000,9022001010976000,9022001010976000,9022001010979000,
               9022001010984000,9022001011002000,9022001011002000,9022001011002000,9022001011002000,9022001011002000,9022001011002000,9022001011002000,
               9022001011002000,9022001011002000,9022001011002010,9022001011002010,9022001011002010,9022001011002010,9022001011002010,9022001011002010,
               9022001011002010,9022001040088000,9022001044000000,9022001044000000,9022001044000000,9022001044000000,9022001044000000,9022001044000000,
               9022001044000000,9022001044000000,9022001044000000,9022001044000010,9022001044000010,9022001044000010,9022001044000010,9022001044000010,
               9022001044000010,9022001044000010,9022001044000010,9022001044000010,9022001044000010,9022001044200000,9022001044200000,9022001044200000,
               9022001044200000,9022001044200000,9022001044200000,9022001044200000,9022001044200000,9022001044200000,9022001044200010,9022001044200010,
               9022001044200010,9022001044200010,9022001044200010,9022001044200010,9022001044200010,9022001044200010,9022001044200010,9022001044200010,
               9022001044200020,9022001044200020,9022001070692000,9023001001011000,9023001001011000,9023001001511000,9023001001511000,9023001001511000,
               9023001001521000,9023001001521000,9023001001521000,9023001002511000,9023001002511000,9023001002521000,9023001002531000,9023001002531000,
               9023001002531000,9023001002531000,9023001005131000,9023001005131000,9023001005131000,9023001005131000)

df_model = df_bus[df_bus['observed_StopAreaID'].isin(model_stops)]
df_model = df_model[df_model['TransportMode']=='BUS']

In [150]:
# Column information

df_model.info()

<class 'pandas.DataFrame'>
Index: 605182 entries, 63098 to 16996819
Data columns (total 29 columns):
 #   Column                                             Non-Null Count   Dtype
---  ------                                             --------------   -----
 0   date                                               605182 non-null  int64
 1   LineNumber                                         605182 non-null  object
 2   LineID                                             605182 non-null  int64
 3   route_id                                           605182 non-null  object
 4   TransportMode                                      605182 non-null  str
 5   direction_id                                       605182 non-null  int64
 6   trip_id                                            605182 non-null  int64
 7   VehicleID                                          400584 non-null  float64
 8   shape_id                                           605182 non-null  int64
 9   planned_departure_sfm                              605182 non-null  int64
 10  planned_departure_tripupdates_sfm                  400575 non-null  float64
 11  stop_sequence                                      605182 non-null  int64
 12  dist_traveled                                      605182 non-null  float64
 13  previous_stop_id                                   605182 non-null  int64
 14  previous_StopAreaID                                605182 non-null  int64
 15  observed_stop_id                                   605182 non-null  int64
 16  observed_StopAreaID                                605182 non-null  int64
 17  scheduled_arrival_time_sfm                         605182 non-null  int64
 18  observed_arrival_time_sfm                          385569 non-null  float64
 19  observed_arrival_delay                             385569 non-null  float64
 20  observed_arrival_uncertainty                       364558 non-null  float64
 21  scheduled_departure_time_sfm                       605182 non-null  int64
 22  observed_departure_time_sfm                        385550 non-null  float64
 23  observed_departure_delay                           385550 non-null  float64
 24  observed_departure_uncertainty                     338481 non-null  float64
 25  tripupdates_and_gtfs_not_merged_within_service_id  605182 non-null  str
 26  tripupdates_not_merged_with_stoptimes_or_trip      605182 non-null  str
 27  stop_headsign                                      605182 non-null  str
 28  ini_delay                                          605182 non-null  float64
dtypes: float64(10), int64(13), object(2), str(4)
memory usage: 138.5+ MB

In [151]:
# Removing columns

df_model['LineID_direction'] = df_model['LineID'].astype(str) + '_' + df_model['direction_id'].astype(str)

df_model = df_model.drop(['LineNumber','route_id','TransportMode','direction_id','trip_id','VehicleID','shape_id',
                          'planned_departure_sfm','planned_departure_tripupdates_sfm','previous_stop_id','observed_stop_id',
                          'observed_arrival_uncertainty','scheduled_departure_time_sfm','observed_departure_time_sfm','observed_departure_delay',
                          'observed_departure_uncertainty','tripupdates_and_gtfs_not_merged_within_service_id',
                          'tripupdates_not_merged_with_stoptimes_or_trip','stop_headsign'], axis=1)

In [152]:
# Classification of delay

cond = [(df_model['observed_arrival_delay'] < -60),
        (df_model['observed_arrival_delay'] >= -60) & (df_model['observed_arrival_delay'] < 150),
        (df_model['observed_arrival_delay'] >= 150) & (df_model['observed_arrival_delay'] < 480),
        (df_model['observed_arrival_delay'] >= 480)]

res = [0,1,2,3]

df_model['delay_cat'] = np.select(cond, res)

In [153]:
# Merge of weather information

import numpy as np

df_model['date_time'] = np.where(df_model['scheduled_arrival_time_sfm']//3600 < 10, 
                                       df_model['date'].astype(str) + '_0' + (df_model['scheduled_arrival_time_sfm']//3600).astype(str), 
                                       df_model['date'].astype(str) + '_' + (df_model['scheduled_arrival_time_sfm']//3600).astype(str))

df_model = pd.merge(df_model, df_wthr, on='date_time', how='left')
df_model.rename(columns={"date_x": "date"}, inplace=True, errors="raise")

df_model.drop(['date_y', 'time'], axis=1, inplace=True)

In [154]:
# Defining coordinates and direction

import math

df_routes = pd.merge(df_routes, df_allstop, on='observed_StopAreaID', how='left')
df_routes.rename(columns={"x": "x_origin", "y": "y_origin"}, inplace=True, errors="raise")
df_model = pd.merge(df_model, df_allstop, on='observed_StopAreaID', how='left')
df_model.rename(columns={"x": "x_dest", "y": "y_dest"}, inplace=True, errors="raise")
df_allstop.rename(columns={"observed_StopAreaID": "previous_StopAreaID"}, inplace=True, errors="raise")
df_model = pd.merge(df_model, df_allstop, on='previous_StopAreaID', how='left')
df_allstop.rename(columns={"previous_StopAreaID": "observed_StopAreaID"}, inplace=True, errors="raise")
df_model.rename(columns={"x": "x_prevstop", "y": "y_prevstop"}, inplace=True, errors="raise")
df_model = pd.merge(df_model, df_routes[['LineID_direction', 'x_origin', 'y_origin']], on='LineID_direction', how='left')
df_model['coming_from_origin'] = np.degrees(np.arctan2(df_model['y_origin'] - df_model['y_dest'], df_model['x_origin'] - df_model['x_dest']))
df_model['coming_from_stop'] = np.degrees(np.arctan2(df_model['y_prevstop'] - df_model['y_dest'], df_model['x_prevstop'] - df_model['x_dest']))

In [155]:
# Get day of the week and month

# df_model['day'] = df_model['date'].str[-2:].astype(int)
df_model['month'] = df_model['date'].astype(str).str[-4:-2].astype(int)
# df_model['yr'] = df_model['date'].str[:4].astype(int)
df_model['date_format'] = pd.to_datetime(df_model['date'], format='%Y%m%d')
df_model['week_day'] = df_model['date_format'].dt.isocalendar().day.astype(int)

In [156]:
df_model.head(10)

,date,LineID,stop_sequence,dist_traveled,previous_StopAreaID,observed_StopAreaID,scheduled_arrival_time_sfm,observed_arrival_time_sfm,observed_arrival_delay,ini_delay,...,y_dest,x_prevstop,y_prevstop,x_origin,y_origin,coming_from_origin,coming_from_stop,month,date_format,week_day
0,20240601,9011001016400000,12,5053.0,9021001011725000,9021001010261000,34782,34985.0,203.0,29.0,...,6.576994e+06,154617.72598,6.575907e+06,152817.11448,6.575387e+06,-133.481897,-75.702176,6,2024-06-01,6
1,20240601,9011001016400000,13,5421.0,9021001010261000,9021001010401000,34867,35119.0,252.0,29.0,...,6.576944e+06,154340.65520,6.576994e+06,152817.11448,6.575387e+06,-125.545142,6.875405,6,2024-06-01,6
2,20240601,9011001016400000,14,5746.0,9021001010401000,9021001010136000,34945,35193.0,248.0,29.0,...,6.577117e+06,153929.50479,6.576944e+06,152817.11448,6.575387e+06,-113.375174,-25.324359,6,2024-06-01,6
3,20240601,9011001016400000,15,6363.0,9021001010136000,9021001010406000,35160,35285.0,125.0,29.0,...,6.577200e+06,153564.67338,6.577117e+06,152817.11448,6.575387e+06,-102.947652,-14.088898,6,2024-06-01,6
4,20240601,9011001016400000,12,5053.0,9021001011725000,9021001010261000,36582,36602.0,20.0,-93.0,...,6.576994e+06,154617.72598,6.575907e+06,152817.11448,6.575387e+06,-133.481897,-75.702176,6,2024-06-01,6
5,20240601,9011001016400000,13,5421.0,9021001010261000,9021001010401000,36667,36680.0,13.0,-93.0,...,6.576944e+06,154340.65520,6.576994e+06,152817.11448,6.575387e+06,-125.545142,6.875405,6,2024-06-01,6
6,20240601,9011001016400000,14,5746.0,9021001010401000,9021001010136000,36745,36750.0,5.0,-93.0,...,6.577117e+06,153929.50479,6.576944e+06,152817.11448,6.575387e+06,-113.375174,-25.324359,6,2024-06-01,6
7,20240601,9011001016400000,15,6363.0,9021001010136000,9021001010406000,36960,36855.0,-105.0,-93.0,...,6.577200e+06,153564.67338,6.577117e+06,152817.11448,6.575387e+06,-102.947652,-14.088898,6,2024-06-01,6
8,20240601,9011001016400000,12,5053.0,9021001011725000,9021001010261000,38382,38602.0,220.0,108.0,...,6.576994e+06,154617.72598,6.575907e+06,152817.11448,6.575387e+06,-133.481897,-75.702176,6,2024-06-01,6
9,20240601,9011001016400000,13,5421.0,9021001010261000,9021001010401000,38467,38722.0,255.0,108.0,...,6.576944e+06,154340.65520,6.576994e+06,152817.11448,6.575387e+06,-125.545142,6.875405,6,2024-06-01,6

In [157]:
df_model.to_csv('202406.csv', index=False)

In [158]:
df_model.info()

<class 'pandas.DataFrame'>
RangeIndex: 605182 entries, 0 to 605181
Data columns (total 48 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   date                        605182 non-null  int64
 1   LineID                      605182 non-null  int64
 2   stop_sequence               605182 non-null  int64
 3   dist_traveled               605182 non-null  float64
 4   previous_StopAreaID         605182 non-null  int64
 5   observed_StopAreaID         605182 non-null  int64
 6   scheduled_arrival_time_sfm  605182 non-null  int64
 7   observed_arrival_time_sfm   385569 non-null  float64
 8   observed_arrival_delay      385569 non-null  float64
 9   ini_delay                   605182 non-null  float64
 10  LineID_direction            605182 non-null  str
 11  delay_cat                   605182 non-null  int64
 12  date_time                   605182 non-null  str
 13  wind_peak                   513707 non-null  float64
 14  solar_rad                   511326 non-null  float64
 15  rain                        511326 non-null  float64
 16  hum                         511326 non-null  float64
 17  temp                        511326 non-null  float64
 18  air_pre                     511326 non-null  float64
 19  wind_spe                    513707 non-null  float64
 20  wind_dir                    513707 non-null  float64
 21  wind_peak-1                 513707 non-null  float64
 22  solar_rad-1                 513707 non-null  float64
 23  rain-1                      513707 non-null  float64
 24  hum-1                       513707 non-null  float64
 25  temp-1                      513707 non-null  float64
 26  air_pre-1                   513707 non-null  float64
 27  wind_spe-1                  513707 non-null  float64
 28  wind_dir-1                  513707 non-null  float64
 29  wind_peak-2                 513707 non-null  float64
 30  solar_rad-2                 513707 non-null  float64
 31  rain-2                      513707 non-null  float64
 32  hum-2                       513707 non-null  float64
 33  temp-2                      513707 non-null  float64
 34  air_pre-2                   513707 non-null  float64
 35  wind_spe-2                  513707 non-null  float64
 36  wind_dir-2                  513707 non-null  float64
 37  x_dest                      605182 non-null  float64
 38  y_dest                      605182 non-null  float64
 39  x_prevstop                  555450 non-null  float64
 40  y_prevstop                  555450 non-null  float64
 41  x_origin                    605182 non-null  float64
 42  y_origin                    605182 non-null  float64
 43  coming_from_origin          605182 non-null  float64
 44  coming_from_stop            555450 non-null  float64
 45  month                       605182 non-null  int64
 46  date_format                 605182 non-null  datetime64[us]
 47  week_day                    605182 non-null  int64
dtypes: datetime64[us](1), float64(36), int64(9), str(2)
memory usage: 221.6 MB